get:
  summary: GET /
  description: Get metadata for the service.
  tags:
    - service metadata
  responses:
    '200':
      description: OK
      content:
        application/hal+json:
          schema:
            $ref: '../schemas/Service.yaml'
