type: object
required:
  - owner
  - specification
  - documentation
properties:
  owner:
    type: string
    format: email
    description: Contact e-mail address of the service owner
  specification:
    type: string
    format: uri
    description: URL of the API specification (YAML or JSON, compliant with [Open API Specification v3](https://github.com/OAI/OpenAPI-Specification/))
  documentation:
    type: string
    format: uri
    description: URL of the API documentation, including general terms and privacy statement
